[package]
name = "common-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
moka = { version = "0.12.13", features = ["future"] }
redis = { version = "1.0.3", features = ["tokio-comp", "json", "cluster"] }
sea-orm = { version = "2.0.0-rc.32", features = ["sqlx-mysql", "runtime-tokio-rustls", "macros"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
tracing-rolling-file = { version = "0.1.3", features = ["non-blocking"] }
tracing-appender = "0.2.4"
urlencoding = "2.1.3"
reqwest = "0.13.2"

