[package]
name = "common-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
tracing-rolling-file = { version = "0.1.3", features = ["non-blocking"] }
tracing-appender = "0.2.4"
sea-orm = { version = "2.0.0-rc.32", features = ["sqlx-mysql", "runtime-tokio-rustls", "macros"] }
redis = { version = "1.0.3", features = ["tokio-comp", "json", "cluster"] }
urlencoding = "2.1.3"
moka = { version = "0.12.13", features = ["future"] }
hmac = "0.13.0-rc.5"
sha2 = "0.11.0-rc.5"
reqwest = "0.13.2"
hex = "0.4.3"
percent-encoding = "2.3.2"
rand = "0.10.0"
base64 = "0.22.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
actix-web = "4.12.1"

