[package]
name = "common-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-rolling-file = { version = "0.1.3", features = ["non-blocking"] }
tracing-appender = "0.2.3"
