[package]
name = "common-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
tracing-rolling-file = { version = "0.1.3", features = ["non-blocking"] }
tracing-appender = "0.2.4"
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "mysql"] }
redis = { version = "1.0.3", features = ["tokio-comp", "json", "cluster"] }
